COMP: NMinimaMaximaImageCalculator initialization
To address:

  FAILED: Wrapping/Modules/Montage/CMakeFiles/MontagePython.dir/itkMaxPhaseCorrelationOptimizerPython.cpp.o
/opt/rh/devtoolset-2/root/usr/bin/g++  -DITK_IO_FACTORY_REGISTER_MANAGER -DMontagePython_EXPORTS -DNDEBUG -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I../../../wrapping -IWrapping/ITKFactoryRegistration -I../../../standalone-x64-build/ITKs/Modules/Segmentation/Watersheds/include -I../../../standalone-x64-build/ITKs/Modules/Video/IO/include -I../../../standalone-x64-build/ITKs/Modules/Video/Filtering/include -I../../../standalone-x64-build/ITKs/Modules/Video/Core/include -I../../../standalone-x64-build/ITKs/Modules/Bridge/VTK/include -I../../../standalone-x64-build/ITKs/Modules/Core/TestKernel/include -I../../../standalone-x64-build/ITKs/Modules/Segmentation/SuperPixel/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/SpatialFunction/include -I../../../standalone-x64-build/ITKs/Modules/Registration/RegistrationMethodsv4/include -I../../../standalone-x64-build/ITKs/Modules/Segmentation/RegionGrowing/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/QuadEdgeMeshFiltering/include -I../../../standalone-x64-build/ITKs/Modules/Registration/Metricsv4/include -I../../../standalone-x64-build/ITKs/Modules/Numerics/Optimizersv4/include -I../../../standalone-x64-build/ITKs/Modules/Segmentation/MarkovRandomFieldsClassifiers/include -I../../../standalone-x64-build/ITKs/Modules/Segmentation/LevelSetsv4/include -I../../../standalone-x64-build/ITKs/Modules/Segmentation/LabelVoting/include -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/libLBFGS/include -I../../../standalone-x64-build/ITKs/Modules/Segmentation/KLMRegionGrowing/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/ImageNoise/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/ImageFusion/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/ImageFrequency/include -I../../../standalone-x64-build/ITKs/Modules/IO/VTK/include -I../../../standalone-x64-build/ITKs/Modules/IO/TransformMatlab/include -I../../../standalone-x64-build/ITKs/Modules/IO/TransformInsightLegacy/include -I../../../standalone-x64-build/ITKs/Modules/IO/TransformHDF5/include -I../../../standalone-x64-build/ITKs/Modules/IO/TransformBase/include -I../../../standalone-x64-build/ITKs/Modules/IO/TransformFactory/include -I../../../standalone-x64-build/ITKs/Modules/IO/Stimulate/include -I../../../standalone-x64-build/ITKs/Modules/IO/SpatialObjects/include -I../../../standalone-x64-build/ITKs/Modules/IO/XML/include -I../../../standalone-x64-build/ITKs/Modules/IO/Siemens/include -I../../../standalone-x64-build/ITKs/Modules/IO/RAW/include -I../../../standalone-x64-build/ITKs/Modules/IO/PNG/include -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/PNG/src -I../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/PNG/src -I../../../standalone-x64-build/ITKs/Modules/IO/NRRD/include -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/NrrdIO/src/NrrdIO -I../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/NrrdIO/src/NrrdIO -I../../../standalone-x64-build/ITKs/Modules/IO/NIFTI/include -I../../../standalone-x64-build/ITKs/Modules/IO/Meta/include -I../../../standalone-x64-build/ITKs/Modules/IO/Mesh/include -I../../../standalone-x64-build/ITKs/Modules/IO/MeshVTK/include -I../../../standalone-x64-build/ITKs/Modules/IO/MeshOFF/include -I../../../standalone-x64-build/ITKs/Modules/IO/MeshOBJ/include -I../../../standalone-x64-build/ITKs/Modules/IO/MeshGifti/include -I../../../standalone-x64-build/ITKs/Modules/IO/MeshFreeSurfer/include -I../../../standalone-x64-build/ITKs/Modules/IO/MeshBYU/include -I../../../standalone-x64-build/ITKs/Modules/IO/MeshBase/include -I../../../standalone-x64-build/ITKs/Modules/Segmentation/Voronoi/include -I../../../standalone-x64-build/ITKs/Modules/IO/MRC/include -I../../../standalone-x64-build/ITKs/Modules/IO/MINC/include -I../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/HDF5/src/itkhdf5 -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/HDF5/src/itkhdf5 -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/MINC/src/libminc/volume_io/Include -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/MINC/src/libminc/libsrc2 -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/MINC/src/libminc/libcommon -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/MINC/src/libminc -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/MINC -I../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/MINC -I../../../standalone-x64-build/ITKs/Modules/IO/LSM/include -I../../../standalone-x64-build/ITKs/Modules/IO/TIFF/include -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/TIFF/src -I../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/TIFF/src/itktiff -I../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/TIFF/src -I../../../standalone-x64-build/ITKs/Modules/IO/JPEG2000/include -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/OpenJPEG/src/openjpeg -I../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/OpenJPEG/src/openjpeg -I../../../standalone-x64-build/ITKs/Modules/IO/JPEG/include -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/JPEG/src -I../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/JPEG/src -I../../../standalone-x64-build/ITKs/Modules/IO/HDF5/include -I../../../standalone-x64-build/ITKs/Modules/IO/GIPL/include -I../../../standalone-x64-build/ITKs/Modules/IO/GE/include -I../../../standalone-x64-build/ITKs/Modules/IO/IPL/include -I../../../standalone-x64-build/ITKs/Modules/IO/GDCM/include -I../../../standalone-x64-build/ITKs/Modules/IO/CSV/include -I../../../standalone-x64-build/ITKs/Modules/IO/Bruker/include -I../../../standalone-x64-build/ITKs/Modules/IO/BioRad/include -I../../../standalone-x64-build/ITKs/Modules/IO/BMP/include -I../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/HDF5/src -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/HDF5/src -I../../../standalone-x64-build/ITKs/Modules/Filtering/GPUThresholding/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/GPUSmoothing/include -I../../../standalone-x64-build/ITKs/Modules/Registration/GPUPDEDeformable/include -I../../../standalone-x64-build/ITKs/Modules/Registration/PDEDeformable/include -I../../../standalone-x64-build/ITKs/Modules/Registration/Common/include -I../../../standalone-x64-build/ITKs/Modules/Registration/GPUCommon/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/GPUImageFilterBase/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/GPUAnisotropicSmoothing/include -I../../../standalone-x64-build/ITKs/Modules/Core/GPUFiniteDifference/include -I../../../standalone-x64-build/ITKs/Modules/Core/GPUCommon/include -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/GIFTI/src/gifticlib -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/GDCM/src/gdcm/Source/DataStructureAndEncodingDefinition -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/GDCM/src/gdcm/Source/MessageExchangeDefinition -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/GDCM/src/gdcm/Source/InformationObjectDefinition -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/GDCM/src/gdcm/Source/Common -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/GDCM/src/gdcm/Source/DataDictionary -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat -I../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/GDCM/src/gdcm/Source/Common -I../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/GDCM -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/Expat/src/expat -I../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/Expat/src/expat -I../../../standalone-x64-build/ITKs/Modules/Numerics/Eigen/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/DisplacementField/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/DiffusionTensorImage/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/Denoising/include -I../../../standalone-x64-build/ITKs/Modules/Segmentation/DeformableMesh/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/Deconvolution/include -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/DICOMParser/src/DICOMParser -I../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/DICOMParser/src/DICOMParser -I../../../standalone-x64-build/ITKs/Modules/Filtering/Convolution/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/FFT/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/Colormap/include -I../../../standalone-x64-build/ITKs/Modules/Segmentation/Classifiers/include -I/opt/python/cp35-cp35m/bin/../include/python3.5m -I../../../standalone-x64-build/ITKs/Modules/Bridge/NumPy/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/BiasCorrection/include -I../../../standalone-x64-build/ITKs/Modules/Numerics/Polynomials/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/AntiAlias/include -I../../../standalone-x64-build/ITKs/Modules/Segmentation/LevelSets/include -I../../../standalone-x64-build/ITKs/Modules/Segmentation/SignedDistanceFunction/include -I../../../standalone-x64-build/ITKs/Modules/Numerics/Optimizers/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/ImageFeature/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/ImageSources/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/ImageGradient/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/Smoothing/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/ImageCompare/include -I../../../standalone-x64-build/ITKs/Modules/IO/ImageBase/include -I../../../ITK-cp35-cp35m-manylinux1_x64/Modules/IO/ImageBase -I../../../standalone-x64-build/ITKs/Modules/Filtering/FastMarching/include -I../../../standalone-x64-build/ITKs/Modules/Core/QuadEdgeMesh/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/DistanceMap/include -I../../../standalone-x64-build/ITKs/Modules/Numerics/NarrowBand/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/BinaryMathematicalMorphology/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/MathematicalMorphology/include -I../../../standalone-x64-build/ITKs/Modules/Segmentation/ConnectedComponents/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/Thresholding/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/LabelMap/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/ImageLabel/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/ImageIntensity/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/Path/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/ImageStatistics/include -I../../../standalone-x64-build/ITKs/Modules/Core/SpatialObjects/include -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/MetaIO/src/MetaIO/src -I../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/MetaIO/src/MetaIO/src -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/ZLIB/src -I../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/ZLIB/src -I../../../standalone-x64-build/ITKs/Modules/Core/Mesh/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/ImageCompose/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/AnisotropicSmoothing/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/ImageGrid/include -I../../../standalone-x64-build/ITKs/Modules/Core/ImageFunction/include -I../../../standalone-x64-build/ITKs/Modules/Core/Transform/include -I../../../standalone-x64-build/ITKs/Modules/Numerics/Statistics/include -I../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/Netlib -I../../../standalone-x64-build/ITKs/Modules/Core/ImageAdaptors/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/CurvatureFlow/include -I../../../standalone-x64-build/ITKs/Modules/Filtering/ImageFilterBase/include -I../../../standalone-x64-build/ITKs/Modules/Core/FiniteDifference/include -I../../../standalone-x64-build/ITKs/Modules/Core/Common/include -I../../../ITK-cp35-cp35m-manylinux1_x64/Modules/Core/Common -I../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/VNL/src/vxl/core -I../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/VNL/src/vxl/vcl -I../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/VNL/src/vxl/v3p/netlib -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/VNL/src/vxl/core -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/KWIML/src -I../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/KWIML/src -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/Eigen3/src -I../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/Eigen3/src -I../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/DoubleConversion/src/double-conversion -I../../../standalone-x64-build/ITKs/Modules/ThirdParty/DoubleConversion/src -I../../../include -Iinclude -I../../../ITK-cp35-cp35m-manylinux1_x64/Wrapping/Typedefs -I../../../standalone-x64-build/ITKs/Wrapping/Generators/Python -isystem ../../../standalone-x64-build/ITKs/Modules/ThirdParty/HDF5/src/itkhdf5/src -isystem ../../../standalone-x64-build/ITKs/Modules/ThirdParty/NIFTI/src/nifti/znzlib -isystem ../../../standalone-x64-build/ITKs/Modules/ThirdParty/NIFTI/src/nifti/niftilib -isystem ../../../standalone-x64-build/ITKs/Modules/ThirdParty/VNL/src/vxl/vcl -isystem ../../../standalone-x64-build/ITKs/Modules/ThirdParty/VNL/src/vxl/v3p/netlib -isystem ../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/KWSys/src -isystem ../../../standalone-x64-build/ITKs/Modules/ThirdParty/Eigen3/src/itkeigen/.. -isystem ../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/Eigen3/src/itkeigen/.. -isystem ../../../standalone-x64-build/ITKs/Modules/ThirdParty/VNL/src/vxl/core/vnl/algo -isystem ../../../standalone-x64-build/ITKs/Modules/ThirdParty/VNL/src/vxl/core/vnl -isystem ../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/NIFTI/src/nifti/znzlib -isystem ../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/NIFTI/src/nifti/niftilib -isystem ../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/HDF5/src/itkhdf5/c++/src -isystem ../../../standalone-x64-build/ITKs/Modules/ThirdParty/HDF5/src/itkhdf5/c++/src -isystem ../../../ITK-cp35-cp35m-manylinux1_x64/Modules/ThirdParty/HDF5/src/itkhdf5/src -Wno-array-bounds  -Wno-array-bounds -O3 -DNDEBUG -fPIC   -fno-strict-aliasing -w -std=c++11 -MD -MT Wrapping/Modules/Montage/CMakeFiles/MontagePython.dir/itkMaxPhaseCorrelationOptimizerPython.cpp.o -MF Wrapping/Modules/Montage/CMakeFiles/MontagePython.dir/itkMaxPhaseCorrelationOptimizerPython.cpp.o.d -o Wrapping/Modules/Montage/CMakeFiles/MontagePython.dir/itkMaxPhaseCorrelationOptimizerPython.cpp.o -c Wrapping/Modules/Montage/itkMaxPhaseCorrelationOptimizerPython.cpp
In file included from ../../../include/itkMaxPhaseCorrelationOptimizer.h:21:0,
                 from ../../../ITK-cp35-cp35m-manylinux1_x64/Wrapping/Typedefs/itkMaxPhaseCorrelationOptimizerSwigInterface.h:18,
                 from Wrapping/Modules/Montage/itkMaxPhaseCorrelationOptimizerPython.cpp:3905:
../../../include/itkNMinimaMaximaImageCalculator.h: In instantiation of ‘static itk::NMinimaMaximaImageCalculator<TInputImage>::Pointer itk::NMinimaMaximaImageCalculator<TInputImage>::New() [with TInputImage = itk::Image<double, 2u>; itk::NMinimaMaximaImageCalculator<TInputImage>::Pointer = itk::SmartPointer<itk::NMinimaMaximaImageCalculator<itk::Image<double, 2u> > >]’:
../../../include/itkMaxPhaseCorrelationOptimizer.h:132:80:   required from ‘static itk::MaxPhaseCorrelationOptimizer<TRegistrationMethod>::Pointer itk::MaxPhaseCorrelationOptimizer<TRegistrationMethod>::New() [with TRegistrationMethod = itk::PhaseCorrelationImageRegistrationMethod<itk::Image<double, 2u>, itk::Image<double, 2u> >; itk::MaxPhaseCorrelationOptimizer<TRegistrationMethod>::Pointer = itk::SmartPointer<itk::MaxPhaseCorrelationOptimizer<itk::PhaseCorrelationImageRegistrationMethod<itk::Image<double, 2u>, itk::Image<double, 2u> > > >]’
Wrapping/Modules/Montage/itkMaxPhaseCorrelationOptimizerPython.cpp:5560:60:   required from here
../../../include/itkNMinimaMaximaImageCalculator.h:123:3: error: conversion from ‘itk::Image<double, 2u>::Pointer {aka itk::SmartPointer<itk::Image<double, 2u> >}’ to non-scalar type ‘itk::NMinimaMaximaImageCalculator<itk::Image<double, 2u> >::ImageConstPointer {aka itk::SmartPointer<const itk::Image<double, 2u> >}’ requested
   NMinimaMaximaImageCalculator() = default;